### ISSUE TITLE
ERROR: Package 'positional-encodings' requires a different Python: 3.6.13 not in '>=3.7'

### ISSUE THREAD

**Issue by ZhangManyuea** [shubhamkaushal765/TransformerQEC#2]
ERROR: Package 'positional-encodings' requires a different Python: 3.6.13 not in '>=3.7'

**Comment by shubhamkaushal765** [comment]
Hi @ZhangManyuea !

I checked my environment which I built on, which was `Python==3.11.9`. Can you run with higher version of Python (`3.11` or `3.10` should also work fine.)?

I will test out on different versions of Python and put out the thresholds later.

Thanks!

**Comment by shubhamkaushal765** [comment]
Hi @ZhangManyuea !

I have used `python==3.11.9` when building Transformer-QEC. You can update your python version to get rid of the error.(preferably `3.11`,  or `3.10` should also work.)

Alternatively, (and more conveniently) you can use a `Dockerfile` to build the environment. In this way, you will have a docker container to work on that won't clutter your system with different version of different softwares.

Paste it in your Dockerfile and run `docker build`
```
FROM pytorch/pytorch:latest

# copy requirements.txt into the docker image
COPY requirements.txt /

RUN pip install -r /requirements.txt
```

Thanks!

**Comment by shubhamkaushal765** [comment]
I have added the Dockerfile to the latest commit on the main branch.

**Comment by ZhangManyuea** [comment]
Thank you very much for your recovery, the problem has been resolved.
